### ISSUE TITLE
[1.2.0 (chaotic-aur)] Installing DXVK and opening Steam on every launch of a game

### ISSUE THREAD

**Issue by SameExpert** [flavioislima/HeroicGamesLauncher#112] opened 2021-01-25 17:21 UTC
It's really nice that you implemented the feature for installing DXVK automatically. But here I found a bug:

1. DXVK should be installed once, but every time I launch a game DXVK is getting installed.
2. Steam also gets opened unnecessarily on every launch of a game, even if it's non-steam (like Uplay).

The game is running well by the way!

**Comment by flavioislima** [comment] 2021-01-25 19:53
What Steam has to do with Heroic for being open with it? This is the first time I heard this. I'll need more info to help with that.
I have steam and it is never opened with heroic, even when steam is already opened. They are completely different.

DXVK is only installed once per prefix, and only on wine prefixes since proton already comes with DXVK on it. 
Unless you're using different wine prefixes for every game or Heroic is not being able to put a file called: 'current_dxvk' on your prefix folder.

I'll try to reproduce the DXVK error, but the Steam one must be something with your machine.

**Comment by flavioislima** [comment] 2021-01-25 21:07
Good catch on the DXVK bug. Fixed on latest release 1.2.1.

**Closed** 2021-01-28 20:22 UTC
