### ISSUE TITLE
Game doesn't start after update to 1.5.2 'Magelan' 

### ISSUE THREAD

**Issue by Sebastian1978** [flavioislima/HeroicGamesLauncher#177] opened 2021-02-18 23:30 UTC
My EGS games are installed via Lutris in /home/igor/Games/epic-games-store/drive_c/Program Files/Epic Games/ and synced
After update to 1.5.2 'Magelan' I can't start my Pillars of Eternity 
Latest log file:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching bcc75c246fe04e45b0c1f1c3fd52503a...
wine: cannot find L"/home/igor/Games/epic-games-store/drive_c/Program Files/Epic Games/PillarsOfEternity/win/PillarsofEternity.exe"

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.10]
 - Version [1.5.2]
-  Game: PillarsofEternity
-  Wine/Proton version: 6.2

**Comment by warriormaster12** [comment] 2021-02-19 07:42
Can confirm the same issue since 1.5. You press play and it immediately stops playing.

**Comment by flavioislima** [comment] 2021-02-19 16:49
@Sebastian1978 
This is quite tricky to debug because Heroic doesnt touch the install files since this is done by Legendary. Unless you tried to move the game and the process wasnt finished.
Or, the game had an update that wasn't finished as well.
Does the executable exist in this folder?

Heroic doesn't launch the game executables directly like lutris, for instance.
Another thing is to check the file `.config/legendary/installed.json` and check if the path to the game folder is correct.

@warriormaster12 do you have exactly the same issue with a missing executable?

**Comment by warriormaster12** [comment] 2021-02-19 18:56
Honestly haven't checked the logs😅. That's my bad. In my case rocket league doesn't launch for some reason 1.5.2 vs 1.4 though I should probably retest. Or should I maybe wait until you release another patch? Noticed that you have pushed some stuff to the repo.

**Comment by flavioislima** [comment] 2021-02-19 19:00
Yeah, I'm finishing testing to release another fix. Might be today or tomorrow.

**Comment by warriormaster12** [comment] 2021-02-19 19:29
No rush mate, better to have a quality patch vs rushed patch.

**Comment by Sebastian1978** [comment] 2021-02-20 08:39
> @Sebastian1978
> This is quite tricky to debug because Heroic doesnt touch the install files since this is done by Legendary. Unless you tried to move the game and the process wasnt finished.
> Or, the game had an update that wasn't finished as well.
> Does the executable exist in this folder?
> 
> Heroic doesn't launch the game executables directly like lutris, for instance.
> Another thing is to check the file `.config/legendary/installed.json` and check if the path to the game folder is correct.
> 
@flavioislima I didnt try to move the game. Also the EXE file exists in its place.
I tried to recover the game via menu but progress bar at  0.00% and nothing happens

**Comment by flavioislima** [comment] 2021-02-20 09:30
If you are syncing the games using the EGS, the game starts using it? Haven't you closed the Egs during a game update?

I think is better just to reinstall it then.

**Comment by Sebastian1978** [comment] 2021-02-20 11:08
@flavioislima yes, the game starts OK using EGS in Lutris. Of couse I closed the EGS

**Comment by Sebastian1978** [comment] 2021-02-20 11:39
Done. But still no progress(

**Comment by Sebastian1978** [comment] 2021-02-20 15:15
How can I reset heroic settings?

**Comment by flavioislima** [comment] 2021-02-20 16:06
@Sebastian1978 I think the issue might be same here on #178 .
can you try doing the same thing as said on one of the last comments?

**Comment by flavioislima** [comment] 2021-02-20 16:10
> How can I reset heroic settings?

you can remove the folder .config/heroic.
This won't erase the games but only the settings

**Comment by kcthrn** [comment] 2021-02-20 18:34
@Sebastian1978, @warriormaster12 This worked for me, so try this:

1. Go to game settings -> Wine
2. Set a separate wine prefix folder
3. Run `winecfg` by clicking "Winecfg". When it starts just close it.
4. Launch game

**Comment by Sebastian1978** [comment] 2021-02-20 19:06
@flavioislima thanks! I added disc Z and all works!

**Comment by flavioislima** [comment] 2021-02-20 22:21
> @Sebastian1978, @warriormaster12 This worked for me, so try this:
> 
> 1. Go to game settings -> Wine
> 2. Set a separate wine prefix folder
> 3. Run `winecfg` by clicking "Winecfg". When it starts just click "OK" to close it.
> 4. Launch game

So this confirms that the issue is with the sandbox command. I'll add it as an option on next release.

**Comment by flavioislima** [comment] 2021-02-22 19:33
So. I"ll close this one since it is duplicated. 
Also it is fixed on the main branch

**Closed by flavioislima** 2021-02-22 19:33 UTC
