### ISSUE TITLE
DXVK missing

### ISSUE THREAD

**Issue by jld3103** [flavioislima/HeroicGamesLauncher#67] opened 2021-01-18 18:53 UTC
When I tried starting a game with DXVK enabled it did do anything.
I ran the app using the terminal and got this:
```log
Error: ENOENT: no such file or directory, open '/home/jld3103/.config/heroic/Tools/DXVK/latest_dxvk'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at installDxvk (/opt/heroic/resources/app.asar/build/utils.js:242:28)
    at launchGame (/opt/heroic/resources/app.asar/build/utils.js:122:15)
    at /opt/heroic/resources/app.asar/build/main.js:126:10
    at electron/js2c/browser_init.js:189:579
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9268)
    at Object.emit (events.js:315:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/jld3103/.config/heroic/Tools/DXVK/latest_dxvk'
}
```

I tried symlinking and copying my DXVK installation from Lutris, but then I got:
```log
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:572:3)
    at tryReadSync (fs.js:357:20)
    at Object.readFileSync (fs.js:394:19)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at installDxvk (/opt/heroic/resources/app.asar/build/utils.js:242:28)
    at launchGame (/opt/heroic/resources/app.asar/build/utils.js:122:15)
    at /opt/heroic/resources/app.asar/build/main.js:126:10
    at electron/js2c/browser_init.js:189:579
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9268)
    at Object.emit (events.js:315:20) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

I suspect the launcher should have downloaded DXVK, but didn't.

**Comment by jld3103** [comment] 2021-01-18 18:54
I see it reads/writes the the latest version name into that file. I'll try to do it manually, but still the bug remains.

**Comment by jld3103** [comment] 2021-01-18 18:58
Yep downloading the dxvk manually and putting the file name into the `latest_dxvk` file does work.

**Comment by flavioislima** [comment] 2021-01-18 19:43
Just tried here with a clean prefix and installation and it worked. Try removing, or moving the .config/heroic folder and open the app from terminal.

For me, that's the output:
`downloaded DXVK
extracting DXVK
DXVK updated!
installing DXVK on '/home/flavio/Games/Prefixes/new_test' WINEPREFIX='/home/flavio/Games/Prefixes/new_test' sh /home/flavio/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh install

 Launch Command:    /media/ssd480/Develop/Electron/heroic/public/bin/legendary launch Curry /usr/bin/wine --wine-prefix '/home/flavio/Games/Prefixes/new_test'`

I suspect you're tried to launch the game before it finishes extracting, so I'll need to check first if DXVK was installed correctly before launching a game.

**Comment by flavioislima** [comment] 2021-01-18 20:04
Ok, so I was able to reproduce the issue and it happens like I said, you start a game without the dxvk has being downloaded.
I'll fix this on next release and wait for the install to finish before starting a game.

To fix for now, just wait for the dxvk is downloaded and extracted.

My log with the error:
`Error: ENOENT: no such file or directory, open '/home/flavio/.config/heroic/Tools/DXVK/latest_dxvk'`

**Comment by jld3103** [comment] 2021-01-22 06:56
The problem seems to be gone. @flavioislima is this fixed?

**Comment by flavioislima** [comment] 2021-01-22 18:59
Yeah, fixed on latest release.  :D

**Closed by flavioislima** 2021-01-22 18:59 UTC

**Comment by BrightTux** [comment] 2021-01-28 09:32
Still facing DXVK missing issue on Manjaro. 
Installed via AUR package.

Manage to solve it by manually symlink the dxvk file to '.tar.gz'

```
bright-amd ~ [16:22:32] ❯ heroic
Updating DXVK to: dxvk-1.7.3L-03f11ba
Error when downloading DXVK
launching Sugar
installing DXVK on ~/.wine WINEPREFIX=~/.wine bash /home/tux/.config/heroic/tools/DXVK/dxvk-1.7.3L-03f11ba.tar.gz/setup_dxvk.sh install
Error: Command failed: WINEPREFIX=~/.wine bash /home/tux/.config/heroic/tools/DXVK/dxvk-1.7.3L-03f11ba.tar.gz/setup_dxvk.sh install
bash: /home/tux/.config/heroic/tools/DXVK/dxvk-1.7.3L-03f11ba.tar.gz/setup_dxvk.sh: No such file or directory

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'WINEPREFIX=~/.wine bash /home/tux/.config/heroic/tools/DXVK/dxvk-1.7.3L-03f11ba.tar.gz/setup_dxvk.sh install',
  stdout: '',
  stderr: 'bash: /home/tux/.config/heroic/tools/DXVK/dxvk-1.7.3L-03f11ba.tar.gz/setup_dxvk.sh: No such file or directory\n'
}
```

Solution:
```
bright-amd ~/.config/heroic/tools/DXVK [16:26:16] ❯ pwd
/home/tux/.config/heroic/tools/DXVK
bright-amd ~/.config/heroic/tools/DXVK [16:25:36] ❯ ln -s ./dxvk-1.7.3L-03f11ba ./dxvk-1.7.3L-03f11ba.tar.gz 

```

**Comment by flavioislima** [comment] 2021-01-28 12:54
The Tools path was changed and some logic to get the DXVK since version 1.2.1. So is needed to delete the folder `.config/heroic/Tools (or tools)` after update
