### ISSUE TITLE
White screen when Installing a large game

### ISSUE THREAD

**Issue by jdfight** [flavioislima/HeroicGamesLauncher#124] opened 2021-01-29 13:35 UTC
**Describe the bug**
When I download and install a large game (20+GB) ,  such as Mechwarrior 5 or Borderlands 2,  the interface turns all white and it seems like the Heroic Launcher is unresponsive.  The game is still downloading and if I leave it for a long time and come back,  the game does eventually install.  I have to close and restart the launcher in order to see my game library again.

**To Reproduce**
1. Go to my library
2. Select a large game to install (>= 20GB)
3. Click install
4. Wait a while and screen turns white.
5. This happens every time.

**Expected behavior**
I expected the Heroic launcher UI to stay visible

**Screenshots**
![Screenshot_20210129_082825](https://user-images.githubusercontent.com/1063108/106280678-37c94900-620c-11eb-902f-a55655cf26d2.png)

**Desktop (please complete the following information):**
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 23.4 GiB of RAM
Graphics Processor: GeForce GTX 1060 3GB/PCIe/SSE2

Game: Mechwarrior 5.  Borderlands 2
Wine/Proton version: Proton-5.21-GE-1

Heroic Games Launcher version: 1.2.2-1  -  heroic-games-launcher-bin 1.2.2-1 (from AUR)

**Comment by DuttaAB-dev** [comment] 2021-01-29 16:50
I am using pop os 20.10 and I can confirm that this is the exact same issue that I am facing right now while downloading GTA V.
![image](https://user-images.githubusercontent.com/61903332/106303266-f2defa00-627f-11eb-938c-cbf1c210ceff.png)
(My system info)
![image](https://user-images.githubusercontent.com/61903332/106303353-0be7ab00-6280-11eb-87c9-9b813013c093.png)
(the main app is all whitened out but the game is downloading in the background as evident from my network usage<sreenshots below>)
![image](https://user-images.githubusercontent.com/61903332/106303514-39ccef80-6280-11eb-9185-5f0d4e3127b2.png)

**Comment by DuttaAB-dev** [comment] 2021-01-29 16:52
By t

> I am using pop os 20.10 and I can confirm that this is the exact same issue that I am facing right now while downloading GTA V.
> ![image](https://user-images.githubusercontent.com/61903332/106303266-f2defa00-627f-11eb-938c-cbf1c210ceff.png)
> (My system info)
> ![image](https://user-images.githubusercontent.com/61903332/106303353-0be7ab00-6280-11eb-87c9-9b813013c093.png)
> (the main app is all whitened out but the game is downloading in the background as evident from my network usage)
> ![image](https://user-images.githubusercontent.com/61903332/106303514-39ccef80-6280-11eb-9185-5f0d4e3127b2.png)

By the way, I am rocking the wayland session. Not sure if this bug exists in xorg.

**Comment by DuttaAB-dev** [comment] 2021-01-29 16:54
And also, my launcher version is 1.2.2
![Uploading image.png…]()

**Comment by flavioislima** [comment] 2021-01-29 18:12
@jdfight are you using wayland as well? I'm using X11 and could not see this issue. I got a froze once but not white screen. I think this might be something with electron, one of the bad things about it since it uses a chromium to render the app. 

Yesterday I downloaded Borderlands 2 and the Pre-sequel and it was ok. But I'll try to reproduce the issue again when I have some time.

**Comment by jdfight** [comment] 2021-01-29 20:31
@flavioislima I am on x11

**Comment by flavioislima** [comment] 2021-01-30 14:31
@jdfight for both borderlands, same config:
![image](https://user-images.githubusercontent.com/26871415/106359002-cecaf980-630f-11eb-8e32-5c90b2eab242.png)
![image](https://user-images.githubusercontent.com/26871415/106359009-d5597100-630f-11eb-8d65-a964b0b7e7a0.png)

the thing about borderlands is that you need to install, on your prefix, the files that comes in the installation folder. There is a file called: BorderlandsInstaller.exe, just drop it on the RUN EXE square and Borderlands should work. I also installed the other exe like vcrun and dotnet that comes on the folder. Except the ond on the AMD folder, MCPP and ImgTec that I dont know that they are.

![image](https://user-images.githubusercontent.com/26871415/106359030-15205880-6310-11eb-8b2c-602057cdaf06.png)

**Comment by jdfight** [comment] 2021-01-30 15:59
Thanks!  I will try those settings out!  I had some decent luck running it with ge-proton-6

**Comment by not-a-dev-stein** [comment] 2021-02-04 19:00
Same thing here, both on Garuda and stock Arch Linux, doesn't even have to be that big of a game, if it takes too long to download the screen goes completely white and doesn't respond until you close and open Heroic again, like this:
![Screenshot_20210204_155606](https://user-images.githubusercontent.com/63420929/106941690-ec2e0800-6701-11eb-9f71-f29ce5a68af0.png)

And when you do reopen you're greeted with this error message:
![Screenshot_20210204_155943](https://user-images.githubusercontent.com/63420929/106941751-0667e600-6702-11eb-9b46-3fbb07799c62.png)

**Comment by flavioislima** [comment] 2021-02-04 19:39
I see. I'll check the error message. Probably the App is being suspended.

Can you try to send heroic to the tray and then returning back after a while to check if it turns white?

**Comment by not-a-dev-stein** [comment] 2021-02-04 19:42
Just did, I'm trying to download Metro: Last Light Redux since earlier today, and anything I do make this happen. Leaving the window open, using other programs and leaving it in the background, closing it to the tray. Everything leads to it.

**Comment by flavioislima** [comment] 2021-02-04 19:56
i see. I'll check why this is happening. Looking at the code, I'm preventing suspension everytime I lock the app, so when one download is starting, or when is repairing, etc. It seems like the main thread is having some error and this is leading to the white screen.

I'll investigate more and try to fix on next release.

**Closed** 2021-02-07 13:14 UTC
