### ISSUE TITLE
Cannot sign in on openSUSE Leap 15.2

### ISSUE THREAD

**Issue by ergpopler** [flavioislima/HeroicGamesLauncher#69] opened 2021-01-18 23:11 UTC
Installing with the RPM worked fine, I can launch, but when i enter by SID and press login the box clears and nothing else happens, i dont get logged in.

**Comment by ergpopler** [comment] 2021-01-18 23:13
same issue with appimage.

**Comment by linuxnutzer** [comment] 2021-01-19 08:15
This issue is related to #66

**Comment by flavioislima** [comment] 2021-01-19 11:33
Can you try downloading and launching legendary? It seems that the error here and on #66 is because leap is missing a legendary dependency. and, for now, heroic won't work if legendary cannot run since heroic is only a frontend for it.

**Comment by flavioislima** [comment] 2021-01-19 20:29
@ergpopler I'll close this on since it is a duplicate of #66. For now, heroic/legendary wont run unless you upgrade python to 3.8 and glibc to 2.27.

**Closed by flavioislima** 2021-01-19 20:29 UTC
