### ISSUE TITLE
Add option the create a desktop shortcut and start menu entry.

### ISSUE THREAD

**Issue by Everest10** [flavioislima/HeroicGamesLauncher#199] opened 2021-02-22 21:39 UTC
Add an option the create a desktop shortcut and start menu entry for the installed games.

**Comment by Peheux** [comment] 2021-02-22 22:10
Duplicate of #140

**Comment by flavioislima** [comment] 2021-02-23 18:40
Yeah, this is planned so I'll close this one and we can talk on #140. :D

**Closed by flavioislima** 2021-02-23 18:40 UTC
