### ISSUE TITLE
What is a "SID information number" ?

### ISSUE THREAD

**Issue by stemy2** [flavioislima/HeroicGamesLauncher#42] opened 2021-01-13 18:13 UTC
Hello,

Can't enter my SID information number becaus i have no idea of what it is. I just logged on epig games and i didn't found anything that looks remotely like a SID information number. I tried to paste the code mentioned as ID under "Account info", but it doesn't work.

**Comment by flavioislima** [comment] 2021-01-13 18:54
Hi!

On the Login Page of Heroic, you will see a message saying about login in on Epic Store, so you need to click on the yellow Link.
then it will open the browser and you will need to log in with your epic account. After doing this you will receive what we call JSON, with information like this one:

`{
"redirectUrl": "https://epicgames.com/account/personal",
"sid": "038f4ab123e2452eab945c5c146bb416f"
}`

Then you need to copy the number on `sid` and paste it on Heroic. Copy only the numbers.

I'll try to make this information easier to understand. And I'm also investigating ways to make it more simple. 😄

**Comment by flavioislima** [comment] 2021-01-14 18:25
I'll close the issue since I guess you're able to login now.

**Closed by flavioislima** 2021-01-14 18:25 UTC

**Comment by apoorv569** [comment] 2021-01-18 18:11
> Hi!
> 
> On the Login Page of Heroic, you will see a message saying about login in on Epic Store, so you need to click on the yellow Link.
> then it will open the browser and you will need to log in with your epic account. After doing this you will receive what we call JSON, with information like this one:
> 
> `{ "redirectUrl": "https://epicgames.com/account/personal", "sid": "038f4ab123e2452eab945c5c146bb416f" }`
> 
> Then you need to copy the number on `sid` and paste it on Heroic. Copy only the numbers.
> 
> I'll try to make this information easier to understand. And I'm also investigating ways to make it more simple. smile

I'm having this problem too, I just updated heroic to the latest version on AUR, but whenever I try to copy the SID, which in you example is `038f4ab123e2452eab945c5c146bb416f`, it fails saying `Error` above the button.

**Comment by flavioislima** [comment] 2021-01-18 18:15
> > Hi!
> > On the Login Page of Heroic, you will see a message saying about login in on Epic Store, so you need to click on the yellow Link.
> > then it will open the browser and you will need to log in with your epic account. After doing this you will receive what we call JSON, with information like this one:
> > `{ "redirectUrl": "https://epicgames.com/account/personal", "sid": "038f4ab123e2452eab945c5c146bb416f" }`
> > Then you need to copy the number on `sid` and paste it on Heroic. Copy only the numbers.
> > I'll try to make this information easier to understand. And I'm also investigating ways to make it more simple. smile
> 
> I'm having this problem too, I just updated heroic to the latest version on AUR, but whenever I try to copy the SID, which in you example is `038f4ab123e2452eab945c5c146bb416f`, it fails saying `Error` above the button.

try to delete .config/legendary folder. Open the app again and try the process one more time.

**Comment by flavioislima** [comment] 2021-01-18 18:17
Just tried and it is working.
Byt the way, make sure to remove the "" of the code. It needs to be only the numbers, like:
411212c9bfbe488ety19c9434aee0f1i

**Comment by apoorv569** [comment] 2021-01-18 19:37
> Just tried and it is working.
> Byt the way, make sure to remove the "" of the code. It needs to be only the numbers, like:
> 411212c9bfbe488ety19c9434aee0f1i

Yes, I tried couple of times, it keeps saying error. Just a thought I have a firewall installed `ufw` could it be the issue?

**Comment by flavioislima** [comment] 2021-01-18 20:06
I dont know, tbh. I dont use it, so it is hard for me to reproduce the error. You can try login with legendary alone to see if you get the same result.

Download Legendary and run on the terminal: `legendary auth`

**Comment by apoorv569** [comment] 2021-01-18 20:14
> I dont know, tbh. I dont use it, so it is hard for me to reproduce the error. You can try login with legendary alone to see if you get the same result.
> 
> Download Legendary and run on the terminal: `legendary auth`
I tried logging in from `legendary`, after entering my SID I'm getting this error

```
[Core] ERROR: Logging in failed with ConnectionError(MaxRetryError("HTTPSConnectionPool(host='account-public-service-prod03.ol.epicgames.com', port=443): Max retries exceeded with url: /account/api/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33cb301880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")), please try again.
[cli] ERROR: Login attempt failed, please see log for details.
```

**Comment by flavioislima** [comment] 2021-01-18 20:17
Yeah, it seems that the problem might be the connection, in this case, might be your firewall. Try adding an exception or disabling then. But I think you might need t to add a permanent exception otherwise you can have errors downloading and launching the games as well.

**Comment by DemonKingSwarn** [comment] 2021-09-16 16:02
> Hi!
> 
> On the Login Page of Heroic, you will see a message saying about login in on Epic Store, so you need to click on the yellow Link.
> then it will open the browser and you will need to log in with your epic account. After doing this you will receive what we call JSON, with information like this one:
> 
> `{ "redirectUrl": "https://epicgames.com/account/personal", "sid": "038f4ab123e2452eab945c5c146bb416f" }`
> 
> Then you need to copy the number on `sid` and paste it on Heroic. Copy only the numbers.
> 
> I'll try to make this information easier to understand. And I'm also investigating ways to make it more simple. 😄

hello, when i am clicking on that message it is not redirecting me to any page. i tried several times now.

**Comment by NorielSylvire** [comment] 2021-10-30 21:28
This doesn't clear anything. How do I receive that json? Where is it stored? How do I store it or whatever? Do I have to code every time I need to log into my account?

**Comment by TRENEEDANAME** [comment] 2021-11-26 21:14
I can't click the link in the app (using Arch Linux, AUR version of the app)
I have the cursor change shape telling it's a link, I click it and nothing happened

**Comment by flavioislima** [comment] 2021-11-27 09:51
> I can't click the link in the app (using Arch Linux, AUR version of the app) I have the cursor change shape telling it's a link, I click it and nothing happened

Heroic will try to open your browser using xdg-open link. Check if you have set your default browser and if this command openb something:
`xdg-open github.com` for instance.

**Comment by kamil-zabierek** [comment] 2021-12-22 19:58
"problem might be the connection" lol... i have the same issue, no other connection problems at all...

**Comment by flavioislima** [comment] 2021-12-22 20:01
From the new beta @kamil-zabierek you dont need the SID anymore, just login from the epic page directly from heroic and it will do the rest:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v1.11.0-beta.3

**Comment by flavioislima** [comment] 2021-12-22 20:02
But OFC, is the Epic services are off, it wont work as well.

**Comment by kamil-zabierek** [comment] 2021-12-22 20:10
thanks, this beta version works. in previous versions:
```
INFO: Logging with Legendary...
stderr: [cli] INFO: Testing existing login data if present...

stderr: urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.legendary.gl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.epicgames.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.epicgames.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.epicgames.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[Core] ERROR: Getting exchange code failed: {'errorCode': 'errors.com.epicgames.unauthorized', 'message': 'You are not authenticated. Please authenticate.', 'correlationId': '8ce9f350-6362-11ec-a535-b3ac41c71187'}

INFO: Frontend: Called Login
stderr: [cli] CRITICAL: No exchange token, cannot login.
```

**Comment by flavioislima** [comment] 2021-12-22 20:12
That's a pretty weird bug. Good that he new version worked then.

**Comment by felisucoibi** [comment] 2022-01-17 18:11
Is not working because of catchpa

**Comment by pellcorp** [comment] 2022-01-23 07:47
The sid method does works, I could not get past the hcaptcha step otherwise.

Anyway I just ran the `/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary authenticate auth` command from terminal after Id logged into firefox browser.   Doing the above command then opened `https://www.epicgames.com/id/api/redirect` which I guess was using the existing session I had already started by logging into firefox.

**Comment by Vitorir** [comment] 2022-03-08 09:08
I have done everything instructed, and keep receiving the same Error message. Fuck.

**Comment by flavioislima** [comment] 2022-03-08 09:18
> I have done everything instructed, and keep receiving the same Error message. Fuck.

We need more info but if you are using Windows, there is an issue on v2.2.2 so try the previous one.
Also, try the Portable version (the one without SETUP in the name)

**Comment by lyndonguitar** [comment] 2022-11-03 10:30
This still isn't working on my end. Clicking the "i" or "the epic store here" doesn;'t open anything

I keep getting logged out when using the Non external login

**Comment by flavioislima** [comment] 2022-11-03 10:35
@lyndonguitar so maybe you have a different issue and we need more information about your System.
Are you on the Steam deck? Linux Flatak?

**Comment by martinderm** [comment] 2022-11-22 21:30
Well my SID as per JSON string ist apparently null....

**Comment by Setitch** [comment] 2023-08-10 14:48
in the json returned:  "sid": null, what to copy now?

**Comment by arielj** [comment] 2023-08-10 20:00
> in the json returned: "sid": null, what to copy now?

sid is always null since a long time ago, the value we have to use now I think it's called `code`
