### ISSUE TITLE
The application loads forever after the latest update

### ISSUE THREAD

**Issue by Ahmed-E-86** [flavioislima/HeroicGamesLauncher#172] opened 2021-02-18 14:24 UTC
The application loads forever after the latest update. That has never happened before. The application freezes while listing games, but the command `legendary list-games` works fine from the terminal.

Kubuntu 20.10
HeroicGamesLauncher version 1.5.1.deb

**Comment by rodrigo21** [comment] 2021-02-18 14:34
I'm having the same problem. Waited the whole night and it was still loading.

I'm on Arch Linux with version 1.5.1.

Just downgraded to version 1.4.0 and it worked.

**Comment by wiryfuture** [comment] 2021-02-18 14:39
I have kubuntu 20.10 as well and just installed 1.5.1 and it loads almost instantly, however the game thumbnails take a moment longer to load than they used to. 
Since I don't have this issue, I'd need some more info before finding a fix.

**Comment by dfireBird** [comment] 2021-02-18 14:44
I have the same error on Arch Linux with version 1.5.1, here is what logged in the terminal: https://gist.github.com/dfireBird/a93cd9287349c7395ac239acf8c443d1

**Comment by wiryfuture** [comment] 2021-02-18 15:07
I think that "stdout" is too big and isn't being handled correctly (the json object with all your games) or the async logic surrounding it isn't being run properly and there's an infinite loop. (library.ts, line 23-64) 
```typescript
export async function getLegendaryGames() {
  const { stdout, stderr } = await execAsync(
    `${legendaryBin} list-games --json`
  )
  if (stdout) {
    const results = JSON.parse(stdout)
    // NEED DOUBLE CHECK IF SOMETHINGS INSIDE IS NEEDED OR ADD MORE STUFF IT REDUCE SIZE OF THE FINAL FILE
    // There is maybe a better way to do that tried with filter but still not work
    results.map((res: any) => {
      delete res.asset_info
      delete res.metadata.creationDate
      delete res.metadata.developerId
      delete res.metadata.dlcItemList
      delete res.metadata.endOfSupport
      delete res.metadata.entitlementName
      delete res.metadata.entitlementType
      delete res.metadata.lastModifiedDate
      delete res.metadata.releaseInfo
      res.metadata.keyImages.map((k: any) => {
        delete k.height
        delete k.md5
        delete k.size
        delete k.uploadedDate
        delete k.width
      })
    })
    const json = JSON.stringify(results)
    return writeFileSync(`${heroicFolder}library.json`, json)
  } else if (stderr) {
    // return a file to avoid infinite loop
    return writeFileSync(
      `${heroicFolder}library.json`,
      '{"result":"noGamesFound"}'
    )
  } else {
    // return a file to avoid infinite loop
    return writeFileSync(
      `${heroicFolder}library.json`,
      '{"result":"noGamesFound"}'
    )
  }
}
```

**Comment by rodrigo21** [comment] 2021-02-18 15:17
I'm also getting the **RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded**. Here the output log: 
[heroic_error.log](https://github.com/flavioislima/HeroicGamesLauncher/files/6003779/heroic_error.log)

I have 158 games on EGS.

**Comment by Zenajj** [comment] 2021-02-18 15:30
Same here, infinite loading loop, nothing happens. 
If I launch from command line, I got this;
`Error occurred in handler for 'readFile': TypeError: JSON.parse(...).map is not a function
    at Object.<anonymous> (/opt/heroic/resources/app.asar/build/legendary_utils/library.js:93:22)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/heroic/resources/app.asar/build/legendary_utils/library.js:5:58)
`
Previous version (1.4.0) worked fine.

**Comment by flavioislima** [comment] 2021-02-18 15:37
Ok I think @wiryfuture is right and the issue is with the new implementation of the readFile function. 
I'll revert this to the previous one and fix on the next hotfix release.

For now just keep with 1.4.0.

**Comment by flavioislima** [comment] 2021-02-18 18:04
Fixed on 1.5.2 Check when you can

**Comment by wiryfuture** [comment] 2021-02-18 18:16
@flavioislima Which keys are needed for each of the games in library.json?

**Comment by flavioislima** [comment] 2021-02-18 18:22
> @flavioislima Which keys are needed for each of the games in library.json?

I guess app_name, title, and metadata. Since everything else is inside metadata like the images, for instance.

**Comment by Ahmed-E-86** [comment] 2021-02-18 19:43
After installing the new version, it asked me to login again. I logged in, but it does not recognize the installed games. I pressed on Refresh Library, but that takes a lot of time to be done, and it does nothing.

**Comment by rodrigo21** [comment] 2021-02-18 20:08
It's working now. Thanks!

**Comment by flavioislima** [comment] 2021-02-18 22:03
> After installing the new version, it asked me to login again. I logged in, but it does not recognize the installed games. I pressed on Refresh Library, but that takes a lot of time to be done, and it did not recognize the installed games.
> 
> Anyway, I imported the installed games manually, but that will be painful if there are a lot of installed games.

If it asked to login again it was because the legendary folder was deleted. And there is where we have the info about the library and installed games. But heroic does not touch this folder, only reads it.

**Comment by Ahmed-E-86** [comment] 2021-02-18 22:14
I was doing something, and I moved this folder. Sorry about that. Anyway, it is fixed. Thanks 👍

**Closed** 2021-02-18 22:15 UTC
